spring:
  profiles:
    active: cloudflare
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://localhost:3306/fileinfo?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dh990921


  upload:
    path: D:/storage/
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 1000MB